# Open ❤ Science

Cards and code to create cards for Open❤️Science, a educational game
based on Apples to Apples.
This game can be played in person or online. If you are interested
in the printed game, please reach out to us ([rdm@vu.nl](mailto:rdm@vu.nl))

# Goal of the Game

Welcome to Open ❤ Science, a card game designed to spark playful yet
insightful dialogues about the Open Science movement. As players delve
into an array of topics related to this stream of research reform,
they are encouraged to reflect on their contributions and beliefs
towards transforming the academic landscape. This game celebrates the
essence of Open Science - fostering connections. It invites players to
look into each other's eyes, exchange ideas, and deepen their
understanding of each other and each other’s research.

# Acknowledgements

This game was created by the **GHOST Collective**, Games of Horror for Open Science Training. GHOST includes:


- Bjorn Bartholdy, TU Delft
- Dafne Jansen, Universiteit Utrecht
- Dan Rudmann, Leiden University
- Elisa Rodenburg, Vrije Universiteit Amsterdam 
- Eva Lekkerkerker, University of Amsterdam
- Lena Karvovskaya, Vrije Universiteit Amsterdam
- Lieke de Boer, Netherlands eScience Center
- Meron Vermaas, Vrije Universiteit Amsterdam
- Stefan Kirsch, Tilburg University
- Stephanie van de Sandt, Vrije Universiteit Amsterdam 
- Tycho Hofstra, Vrije Universiteit Amsterdam 

Previous GHOST collective games include the [Software Horror Escape Room](https://nlesc.github.io/softwarehorrorgame/SoftwareHorrorGame.html) and [Data Horror Escape Room](https://sites.google.com/vu.nl/datahorror/home?authuser=0)

