---
title: Rules of the Game
---

🧍3-7 players ⏰ 5 minutes - 24 hours 🏋️ difficulty level: researcher friendly

Game Mechanics:
The game is played with two types of cards: red and white. Red cards feature a variety of Open Science concepts, from abstract to highly practical, each accompanied by a brief description and a hyperlink for further exploration. White cards, meanwhile, embody the core principles of Open Science. The challenge lies in finding the most fitting match between a white principle card and a red concept card. The role of the Open Science Cupid is to determine which pairing shines the brightest!
To begin, shuffle the red cards and deal five to each player, placing the remainder in a face-down stack. Then, shuffle the white cards to create another stack. Choose the first Open Science Cupid, who will unveil the first white card from the pile. Players then each select one of their red cards to play. The Cupid has the discretion to set the criteria for the most harmonious match. The winner of the round claims the white card, earning a point. The Cupid's role then passes to the next player on the left. Continue the game until all white cards have been awarded.

## Variation 1: Speed Dating

In this fast-paced twist, after the Cupid presents the white card for the round, players submit their red cards anonymously and face-down. The Cupid then chooses their favorite match and shares the rationale behind their decision with the group.

## Variation 2: Open Declaration

For a more open challenge, after the Cupid reveals the white card, players place their red cards face up and articulate their reasons for the pairing. The Cupid is then tasked with selecting the winning match based on the strength of the arguments presented
