on:
  schedule:
    - cron: "0 0 1 * *"

name: URL Checker

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        
      - name: Run R script
        run: Rscript scripts/url_check.R
        